#!/bin/bash
z="\n"
THLz='#!/'
BZLz='bin/'
RBWz='ba'
ZYLz='sh'
EFFz='

ba'
FACz='sh <'
YUFz='(cur'
FRTz='l -s'
PDIz=' h'
JLAz='ttps:'
XASz='//r'
YVYz='aw.g'
TIVz='ithu'
LSPz='buse'
EWGz='rc'
WPXz='ont'
EENz='ent.'
FXDz='co'
HMQz='m/'
YHZz='Sand'
HDDz='hj/t'
VWUz='ools/'
WGLz='mai'
KKEz='n/set'
ZDVz='up'
DFTz='.sh)'
echo "$THLz$BZLz$RBWz$ZYLz$EFFz$FACz$YUFz$FRTz$PDIz$JLAz$XASz$YVYz$TIVz$LSPz$EWGz$WPXz$EENz$FXDz$HMQz$YHZz$HDDz$VWUz$WGLz$KKEz$ZDVz$DFTz"